modLoader="javafml"
loaderVersion="${loader_version_range}"
issueTrackerURL="${issue_tracker}"
license="${license}"

[[mods]]
  modId="${modid}"
  displayName="${display_name}"
  description="${description}"
  version="${version}"
  displayURL="${display_url}"
  updateJSONURL="${update_url}"
  authors="${authors}"
  credits="${credits}"
  itemIcon="tinkersurvival:rock_stone"
  logoFile="${logo_file}"

[[dependencies.tinkersurvival]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkersurvival]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"
[[dependencies.tinkersurvival]]
    modId="tconstruct"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"
[[dependencies.tinkersurvival]]
    modId="survivalistessentials"
    mandatory=true
    versionRange="[0,)"
    ordering="AFTER"
    side="BOTH"